### ISSUE TITLE
Add missing TF schema to CRD schema mappings

### ISSUE THREAD

**Issue by stuartleeks** [lawrencegripper/tfoperatorbridge#18]
Looking at the generated CRD schema for `app-services` (from `kubectl get customresourcedefinitions.apiextensions.k8s.io  app-services.azurerm.tfb.local -o yaml`):

![image](https://user-images.githubusercontent.com/1824461/87536566-33cf4280-c691-11ea-899f-4a34a4c930e0.png)

there are some missing fields (e.g. `site_config`) compared to the TF schema (from https://www.terraform.io/docs/providers/azurerm/r/app_service.html):

![image](https://user-images.githubusercontent.com/1824461/87536627-4a759980-c691-11ea-8c8d-053096bfe838.png)

(It might be that these show only as `BlockTypes` rather than `Attributes`. Currently `addBlockToSchema` only processes `Attributes`)

**Comment by jjcollinge** [comment]
@stuartleeks yes these are nestedBlocks rather than attributes so need to be handled accordingly. This issue causes skipped values in reconciliation too where we cannot find the key in the schema: https://github.com/lawrencegripper/tfoperatorbridge/blob/d3644e1cde48e3d008a7ba58986e28d1cf97406f/reconcile.go#L573

**Comment by jjcollinge** [comment]
Started working on this #55

**Comment by jjcollinge** [comment]
closed by #55
